import { RADIUS, SPACING, TYPE_STYLES } from '../../theme';

export const CONTAINER_MANAGEMENT_TOKENS = {
  CONTENT_PADDING_X: SPACING.xl,
  CONTENT_PADDING_Y: SPACING.lg,
  SECTION_GAP: SPACING.md,
  PANEL_MIN_WIDTH: SPACING['3xl'] * 5,
  PANEL_PADDING: SPACING.md,
  PANEL_RADIUS: RADIUS.sm,
  ROW_GAP: SPACING.sm,
  ROW_MIN_HEIGHT: SPACING.md * 2,
  TITLE_TYPE: TYPE_STYLES.sectionTitle,
  BODY_TYPE: TYPE_STYLES.bodySm,
};
